### ISSUE TITLE
CREATE_SYMLINKS creates bad symlink

### ISSUE THREAD

**Issue by azazar** [antage/docker-apache2-php5#4]
CREATE_SYMLINKS doesn't work as expected. It is not supposed to create `html` symlink in `app` directory, when set to `/home/ftpaccount/tds.xdmanage.com>/var/www/html`.

Here's docker-compose.yml, that I use for my webserver.

```
version: '3'
services:
    itds-php:
        image: antage/apache2-php5:latest
        ports:
            - "8476:8080"
        volumes:
            - ./app:/var/www/html
        environment:
            CREATE_SYMLINKS: "/home/ftpaccount/tds.xdmanage.com>/var/www/html"
            APACHE_MODS: "rewrite auth_basic"
            APACHE_ALLOW_OVERRIDE: "All"
            APACHE_SERVER_NAME: "itds"
            APACHE_CUSTOMLOG: '"|/bin/cat" combined'
            APACHE_ERRORLOG: '"|/bin/cat"'
            PHP_MODS: "pdo pdo_mysql"
            PHP_SMTP: "localhost"
            PHP_SMTP_FROM: "nobody"
        restart: always
```
